# Generated by Django 2.2.19 on 2021-04-14 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('status', models.TextField(verbose_name='статус')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
            ],
        ),
    ]
